default['cc_policy_windows_security_options']['policy_map'] = {components: [
                              {
                               identified_by: 'value',
                               id: 'os:windows',
                               enforced_by: [{
                                                policy: 'policy_windows_security_options',
                                                enabled: false }]
                              }               

                           
                             ]
                          }
default['cc_policy_windows_security_options']['ui_metadata']['policy_windows_security_options'] = {
           policy:"policy_windows_security_options",
           display_name:"policy_windows_security_options",
           techspec: '<b>CSD_Win2008:</b>NA<br><b>-CSD_Win2012:</b>NA<br><b>-CSD_Win2016:</b>GZ.1.9.3, GZ.1.9.4, GZ.1.9.6, GZ.1.9.7, GZ.1.9.8, GZ.1.9.9, GZ.1.9.10, GZ.1.9.11, GZ.1.9.12, GZ.1.9.14, GZ.1.9.15<br><b>-ITCS_Win2008:</b>NA<br><b>-ITCS_Win2012:</b>NA<br>',
              attributes:[
                {key: 'allow_modify_gpo',
                   type: 'Boolean',
                   display_type: 'single_select',
                   display_name: 'Allow GPO Remediation', 
                   validator: '',
                   units: '',
                   options: '[{"key": "true", "value": "true"}, {"key": "false", "value": "false"}]',
                   hint: 'Allow recipe to modify GPO settings.',
                   default: false},
                {key:"new_guest_name",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Accounts: Rename guest account <br/>(key: NewGuestName)",
                   validator:"^[a-zA-Z0-9_() `~!@#$%&'^-]*$",
                   units:"string",
                   options:[],
                   hint:"New name for the Built-in guest account.<br/>Valid User name should not have following characters:<br/><b>\"\\\ / | [ ] : < > , . : ; ? * + =</b>"},
                {key:"enable_guest_account",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Accounts: Guest account status <br/>(key: EnableGuestAccount)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Guest account status.<br/>0: disabled;<br/>1: enabled."},
                {key:"filter_administrator_token",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Admin Approval Mode for the built-in Administrator account <br/>(key: FilterAdministratorToken)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Admin Approval Mode for the Built-in Administrator account.<br/>0: disabled,<br/>1: enabled."},
                {key:"enable_uia_desktop_toggle",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Allow UIAccess applications to prompt for elevation without using the secure desktop <br/>(key: EnableUIADesktopToggle)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Allow UIAccess applications to prompt for elevation without using the secure desktop.<br/>0: disabled;<br/>1: enabled."},
               {key:"consent_prompt_behavior_admin",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Behavior of the elevation prompt for administrators <br/>(key: ConsentPromptBehaviorAdmin)",
                   validator:"^[0-5]$",
                   units:"bytes",
                   options:[],
                   hint:"Behavior of the elevation prompt for administrators." +
                        "<br/>0: Elevate without prompting," +
                        "<br/>1: Prompt for credentials on the secure desktop," +
                        "<br/>2: Prompt for consent on the secure desktop," +
                        "<br/>3: Prompt for credentials," +
                        "<br/>4: Prompt for consent," +
                        "<br/>5: Prompt for consent for non-Windows binaries."},
                {key:"consent_prompt_behavior_user",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Behavior of the elevation prompt for standard users <br/>(key: ConsentPromptBehaviorUser)",
                   validator:"^[013]$",
                   units:"bytes",
                   options:[],
                   hint:"Behavior of the elevation prompt for standard users." +
                        "<br/>0: Automatically deny elevation requests;" +
                        "<br/>1: Prompt for credentials on the secure desktop," +
                        "<br/>3: Prompt for credentials."},
                {key:"enable_installer_detection",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Detect application installations and prompt for elevation <br/>(key: EnableInstallerDetection)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Detect application installations and prompt for elevation.<br/>0: disabled,<br/>1: enabled."},
                {key:"validate_admin_code_signatures",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Only elevate executables that are signed and validated <br/>(key: ValidateAdminCodeSignatures)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Only elevate executables that are signed and validated.<br/>0: disabled;<br/>1: enabled"},
                {key:"enable_secure_uia_paths",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Only elevate UIAccess applications that are installed in secure locations <br/>(key: EnableSecureUIAPaths)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Only elevate UIAccess applications that are installed in secure locations.<br/>0: disabled,<br/>1: enabled."},
                {key:"prompt_on_secure_desktop",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Switch to the secure desktop when prompting for elevation <br/>(key: PromptOnSecureDesktop)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Switch to the secure desktop when prompting for elevation.<br/>0: disabled,<br/>1: enabled."},
                {key:"enable_virtualization",
                   type:"text",
                   display_type:"text_box",
                   display_name:"User Account Control: Virtualize file and registry write failures to per-user locations <br/>(key: EnableVirtualization)",
                   validator:"^[01]$",
                   units:"bytes",
                   options:[],
                   hint:"Virtualize file and registry write failures to per-user locations.<br/>0: disabled,<br/>1: enabled."}
            ],
        validator:"",
        units:"",
        hint:""
        }

