default['cc_policy_windows_log_retention']['policy_map'] = {components: [
                              {
                               identified_by: 'value',
                               id: 'os:windows',
                               enforced_by: [{
                                                policy: 'policy_windows_log_retention',
                                                enabled: true}]
                              }               

                           
                             ]
                          }
default['cc_policy_windows_log_retention']['ui_metadata']['policy_windows_log_retention'] = {
           policy:"policy_windows_log_retention",
           display_name:"policy_windows_log_retention",
           techspec: '<b>CSD_Win2008:</b>YO.1.8.33, YO.1.8.34, YO.1.8.35<br><b>-CSD_Win2012:</b>ED.1.8.33, ED.1.8.34, ED.1.8.35<br><b>-CSD_Win2016:</b>GZ.1.8.31, GZ.1.8.32, GZ.1.8.33<br><b>-ITCS_Win2008:</b>Section 5.1<br><b>-ITCS_Win2012:</b>Section 5.1<br>',
              attributes:[
                {key: 'allow_modify_gpo',
                   type: 'Boolean',
                   display_type: 'single_select',
                   display_name: 'Allow GPO Remediation',
                   validator: '',
                   units: '',
                   options: '[{"key": "true", "value": "true"}, {"key": "false", "value": "false"}]',
                   hint: 'Allow recipe to modify GPO settings.',
		   default: false},
                {key:"secretention",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Days to Retain Security Log for all Windows editions",
                   validator:"\-1|0|[0-9]*",
                   units:"days",
                   options:[],
                   hint:"Number of Days to Retain Security Logs. 0 means OverwriteAsNeeded, -1 means NeverOverwrite."},
		{key:"secbehavior",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Security Log Behavior for all Windows editions",
                   validator:"Never|DoNotOverwrite|OverwriteOlder|OverwriteAsNeeded",
                   units:"",
                   options:[],
                   hint:"Behavior of the Security Log Overwrite.<br/>Valid values:&lt;empty&gt;, Never, DoNotOverwrite, OverwriteOlder, OverwriteAsNeeded"},
                {key:"secsize",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Size of Security Log for all Windows editions",
                   validator:"",
                   units:"bytes",
                   options:[],
                   hint:"Size of the Security Log"},
                {key:"appretention",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Days to Retain Application Log for Windows 2008/2012",
                   validator:"\-1|0|[0-9]*",
                   units:"days",
                   options:[],
                   hint:"Number of Days to Retain Application Logs for Windows 2008/2012. 0 means OverwriteAsNeeded, -1 means NeverOverwrite."},
				{key:"appretention_2016",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Days to Retain Application Log for Windows 2016",
                   validator:"\-1|0|[0-9]*",
                   units:"days",
                   options:[],
                   hint:"Number of Days to Retain Application Logs for Windows 2016. 0 means OverwriteAsNeeded, -1 means NeverOverwrite."},
				{key:"appbehavior",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Application Log Behavior for Windows 2008/2012",
                   validator:"Never|DoNotOverwrite|OverwriteOlder|OverwriteAsNeeded",
                   units:"",
                   options:[],
                   hint:"Behavior of the Application Log Overwrite for Windows 2008/2012.<br/>Valid values:&lt;empty&gt;, Never, DoNotOverwrite, OverwriteOlder, OverwriteAsNeeded"},
				{key:"appbehavior_2016",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Application Log Behavior for Windows 2016",
                   validator:"Never|DoNotOverwrite|OverwriteOlder|OverwriteAsNeeded",
                   units:"",
                   options:[],
                   hint:"Behavior of the Application Log Overwrite for Windows 2016.<br/>Valid values:&lt;empty&gt;, Never, DoNotOverwrite, OverwriteOlder, OverwriteAsNeeded"},
                {key:"appsize",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Size of Application Log for all Windows editions",
                   validator:"",
                   units:"bytes",
                   options:[],
                   hint:"Size of the Application Log"},
                {key:"sysretention",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Days to Retain System Log for Windows 2008/2012",
                   validator:"\-1|0|[0-9]*",
                   units:"days",
                   options:[],
                   hint:"Number of Days to Retain System Logs for Windows 2008/2012. 0 means OverwriteAsNeeded, -1 means NeverOverwrite."},
				{key:"sysretention_2016",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Days to Retain System Log for Windows 2016",
                   validator:"\-1|0|[0-9]*",
                   units:"days",
                   options:[],
                   hint:"Number of Days to Retain System Logs for Windows 2016. 0 means OverwriteAsNeeded, -1 means NeverOverwrite."},
				{key:"sysbehavior",
                   type:"text",
                   display_type:"text_box",
                   display_name:"System Log Behavior for Windows 2008/2012",
                   validator:"Never|DoNotOverwrite|OverwriteOlder|OverwriteAsNeeded",
                   units:"",
                   options:[],
                   hint:"Behavior of the System Log Overwrite for Windows 2008/2012.<br/>Valid values:&lt;empty&gt;, Never, DoNotOverwrite, OverwriteOlder, OverwriteAsNeeded"},
				{key:"sysbehavior_2016",
                   type:"text",
                   display_type:"text_box",
                   display_name:"System Log Behavior for Windows 2016",
                   validator:"Never|DoNotOverwrite|OverwriteOlder|OverwriteAsNeeded",
                   units:"",
                   options:[],
                   hint:"Behavior of the System Log Overwrite for Windows 2016.<br/>Valid values:&lt;empty&gt;, Never, DoNotOverwrite, OverwriteOlder, OverwriteAsNeeded"},
                {key:"syssize",
                   type:"text",
                   display_type:"text_box",
                   display_name:"Size of System Log for all Windows editions",
                   validator:"",
                   units:"bytes",
                   options:[],
                   hint:"Size of the System Log"}
			],
		validator:"",
        units:"",
        hint:""
        }

              
