# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2018 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================
name             'cc_policies_linux'
version          '1.0.140'
maintainer       'Robert Filepp'
maintainer_email 'filepp@us.ibm.com'
license          'IBM Proprietary - All rights reserved'
description      'recipe wrapper'
depends           'chef_handler'
depends           'cobalt_ohai'
# compliance policies for linux os resources
depends           'cc_policy_linux_auditd', '= 1.0.7'
depends           'cc_policy_linux_db2', '= 1.0.6'
depends           'cc_policy_linux_delete_files', '= 1.0.2'
depends           'cc_policy_linux_directory_perms', '= 1.0.3'
depends           'cc_policy_linux_duplicate_uid_gid', '= 1.0.2'
depends           'cc_policy_linux_enforce_pam_inheritance', '= 1.0.1'
depends           'cc_policy_linux_entire_dir_perms', '= 1.0.5'
depends           'cc_policy_linux_failed_login_retries', '= 1.0.13'
depends           'cc_policy_linux_file_permissions', '= 1.0.5'
depends           'cc_policy_linux_ftp', '= 1.0.1'
depends           'cc_policy_linux_inactive_accounts', '= 1.0.3'
depends           'cc_policy_linux_log_retention', '= 1.0.7'
depends           'cc_policy_linux_mcafee', '= 1.0.2'
depends           'cc_policy_linux_mongodb', '= 1.0.1'
depends           'cc_policy_linux_motd', '= 1.0.2'
depends           'cc_policy_linux_motd_v2', '= 1.0.2'
depends           'cc_policy_linux_nis', '= 1.0.0'
depends           'cc_policy_linux_nntp', '= 1.0.5'
depends           'cc_policy_linux_no_loginpassword', '= 1.0.1'
depends           'cc_policy_linux_ntpd', '= 1.0.5'
depends           'cc_policy_linux_null_password', '= 1.0.6'
depends           'cc_policy_linux_openldap', '= 1.0.2'
depends           'cc_policy_linux_osr_full_path', '= 1.0.7'
depends           'cc_policy_linux_pam_default_deny_all', '= 1.0.3'
depends           'cc_policy_linux_pass_max_age', '= 1.0.6'
depends           'cc_policy_linux_pass_min_age', '= 1.0.4'
depends           'cc_policy_linux_pass_min_len', '= 1.0.0'
depends           'cc_policy_linux_password_history', '= 1.0.2'
depends           'cc_policy_linux_port_vulnerabilities', '= 1.0.4'
depends           'cc_policy_linux_priv_group_membership', '= 1.0.5'
depends           'cc_policy_linux_qradar', '= 1.0.3'
depends           'cc_policy_linux_rlogin', '= 1.0.2'
depends           'cc_policy_linux_secure_internal_services', '= 1.0.1'
depends           'cc_policy_linux_session', '= 1.0.10'
depends           'cc_policy_linux_security_vulnerabilities', '= 1.0.2'
depends           'cc_policy_linux_snmpd', '= 1.0.5'
depends           'cc_policy_linux_ssh_keys', '= 1.0.3'
depends           'cc_policy_linux_ssh_restriction', '= 1.0.1'
depends           'cc_policy_linux_sshd', '= 1.0.3'
depends           'cc_policy_linux_sudo', '= 1.0.4'
depends           'cc_policy_linux_sysctl_network', '= 1.0.1'
depends           'cc_policy_linux_syslog', '= 1.0.2'
depends           'cc_policy_linux_syslog_v2', '= 1.0.0'
depends           'cc_policy_linux_tftp', '= 1.0.5'
depends           'cc_policy_linux_unsafe_services', '= 1.0.2'
depends           'cc_policy_linux_was', '= 1.0.7'
depends           'cc_policy_linux_xhost', '= 1.0.4'
depends           'cc_policy_linux_docker_cfg_files', '= 1.0.2'

attribute        'cc_policies_linux/policy_map',
                 description: 'policy map',
                 type: 'string'
