default['cc_policy_linux_priv_group_membership']['policy_map'] = {"components" => [
                              {
                               identified_by: 'value',
                               id: 'os:linux',
                               "enforced_by" => [{
                                                policy: 'policy_linux_priv_group_membership',
                                                enabled: true}]
                              }


                             ]
                          }

default['cc_policy_linux_priv_group_membership']['ui_metadata']['policy_linux_priv_group_membership'] = {
           "policy"=>"policy_linux_priv_group_membership",
           "display_name"=>"policy_linux_priv_group_membership",
           "techspec"=> '<b>CSD:</b>NA<br><b>-ITCS:</b>NA<br>',
              "attributes"=>[
                {
                    "key"=>"allowed_membership",
                    "type"=>"complex_hash",
                    "display_name"=>"allowed membership",
                    "display_type"=>"object_set",
		"attributes" => [{

		    "options"=>"editable",
				"display_type"=>"string_array"
			
		}],
		     "add_remove"=>"enable",
                    "validator"=>"",
                    "units"=>"",
                    "options"=>[],
                    "hint"=>"List of groups and their allowed users.",
      },

                   {"key"=>"priv_gid_ranges",
                   "type"=>"csv_hashmap",
                   "display_type"=>"string_array",
                   "display_name"=>"priv gid ranges for all OS",
                   "validator"=>"", 
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"OS GIDs which should be considered privileged for all OS, it will be merged with other OS specified GID ranges."},
                  {"key"=>"priv_gid_ranges_rhel_5_and_6",
                   "type"=>"csv_hashmap",
                   "display_type"=>"string_array",
                   "display_name"=>"priv gid ranges rhel 5 and 6",
                   "validator"=>"", 
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"OS GIDs which should be considered privileged for Red Hat 5 and 6."},
                   {"key"=>"priv_gid_ranges_rhel_7",
                   "type"=>"csv_hashmap",
                   "display_type"=>"string_array",
                   "display_name"=>"priv gid ranges rhel 7",
                   "validator"=>"", 
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"OS GIDs which should be considered privileged for Red Hat 7 and above."},
                   {"key"=>"priv_gid_ranges_sles_10",
                   "type"=>"csv_hashmap",
                   "display_type"=>"string_array",
                   "display_name"=>"priv gid ranges sles 10",
                   "validator"=>"", 
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"OS GIDs which should be considered privileged for SUSE 10 and above."},
                   {"key"=>"priv_gid_ranges_debian_7",
                   "type"=>"csv_hashmap",
                   "display_type"=>"string_array",
                   "display_name"=>"priv gid ranges debian 7",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"OS GIDs which should be considered privileged for Debian 7 and above."},
                  {"key"=>"user_whitelist",
                   "type"=>"csv",
                   "display_name"=> "User Names to Exclude",
                   "display_type"=>"string_array",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"List of users to exclude"},
                  {"key"=>"group_whitelist",
                   "type"=>"csv",
                   "display_name"=> "Group names to Exclude",
                   "display_type"=>"string_array",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"List of group names to exclude."},
                  {"key"=>"exempt_accounts_without_shell",
                   "type"=>"Boolean",
                   "display_type"=>"single_select",
                   "display_name"=> "Exempt Accounts without Shell",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"User accounts with their shell set to /sbin/nologin or /bin/false are excluded from privileged group checking."},
                  {"key"=>"exempt_locked_accounts",
                   "type"=>"Boolean",
                   "display_type"=>"single_select",
                   "display_name"=> "Exempt Locked Accounts",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"User accounts which are locked are excluded from privileged group checking."},
                  {"key"=>"exempt_disabled_accounts",
                   "type"=>"Boolean",
                   "display_type"=>"single_select",
                   "display_name"=> "Exempt Disabled Accounts",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"Disabled User accounts (!, !!, *, x, or length of password<= 2 chars in the password field of /etc/shadow and without passwords) are excluded from privileged group checking."},
                  {"key"=>"exempt_pam_denied_user_list",
                   "type"=>"Boolean",
                   "display_type"=>"single_select",
                   "display_name"=> "Exempt users in the pam denied user list",
                   "validator"=>"",
                   "units"=>"",
                   "options"=>[],
                   "hint"=>"User accounts which have been denied via a denied user list are exempt from the specified checks."}
               ],
             "validator"=>"",
             "units"=>"",
             "hint"=>""}
